// Auto-generated on 2025-07-03T17:49:57.617Z
export const hr = [
	{
		fullName: 'АПЕКСИМОВА Ирина Викторовна',
		position: 'директор',
		organization: 'ГБУК г. Москвы "Московский театр на Таганке"',
		organizationInn: '7709010548',
		hrId: '1',
		photo: '1.jpg',
		contractStart: '',
		contractEnd: '',
		phone: '',
		email: '',
		titles: '',
		biography: '',
		linkToTheaterSite: '',
		wikiUrl: ''
	},
	{
		fullName: 'АСЛАНОВ Эдуард Эдуардович',
		position: 'директор',
		organization: 'ГБУК г. Москвы "Московский театр иллюзии"',
		organizationInn: '7720056169',
		hrId: '2',
		photo: '2.jpg',
		contractStart: '',
		contractEnd: '',
		phone: '',
		email: '',
		titles: '',
		biography: '',
		linkToTheaterSite: '',
		wikiUrl: ''
	},
	{
		fullName: 'АСТРАХАН Дмитрий Хананович',
		position: 'художественный руководитель',
		organization: 'ГБУК г. Москвы "Театр на Трубной"',
		organizationInn: '7707064139',
		hrId: '3',
		photo: '3.jpg',
		contractStart: '',
		contractEnd: '',
		phone: '',
		email: '',
		titles: '',
		biography: '',
		linkToTheaterSite: '',
		wikiUrl: ''
	},
	{
		fullName: 'АСТАХОВ Никита Сергеевич',
		position: 'художественный руководитель',
		organization: 'ГБУК г. Москвы "РДТ "ГЛАС"',
		organizationInn: '7702069567',
		hrId: '4',
		photo: '4.jpg',
		contractStart: '',
		contractEnd: '',
		phone: '',
		email: '',
		titles: '',
		biography: '',
		linkToTheaterSite: '',
		wikiUrl: ''
	},
	{
		fullName: 'БАБКИНА Надежда Георгиевна',
		position: 'художественный руководитель',
		organization: 'ГБУК г. Москвы "МГАТ "Русская песня"',
		organizationInn: '7714039052',
		hrId: '5',
		photo: '5.jpg',
		contractStart: '',
		contractEnd: '',
		phone: '',
		email: '',
		titles: '',
		biography: '',
		linkToTheaterSite: '',
		wikiUrl: ''
	},
	{
		fullName: 'БАБКИНА Надежда Георгиевна',
		position: 'директор',
		organization: 'ГБУК г. Москвы "МГАТ "Русская песня"',
		organizationInn: '7714039052',
		hrId: '5',
		photo: '5.jpg',
		contractStart: '',
		contractEnd: '',
		phone: '',
		email: '',
		titles: '',
		biography: '',
		linkToTheaterSite: '',
		wikiUrl: ''
	},
	{
		fullName: 'БЕЛЕВИЧ Татьяна Георгиевна',
		position: 'директор',
		organization: 'ГБУК г. Москвы "РДТ "ГЛАС"',
		organizationInn: '7702069567',
		hrId: '6',
		photo: '6.jpg',
		contractStart: '',
		contractEnd: '',
		phone: '',
		email: '',
		titles: '',
		biography: '',
		linkToTheaterSite: '',
		wikiUrl: ''
	},
	{
		fullName: 'БЕЛЯЕВА Галина Михайловна',
		position: 'директор',
		organization: 'ГБУК г. Москвы ДДТ "На набережной"',
		organizationInn: '7704224472',
		hrId: '7',
		photo: '7.jpg',
		contractStart: '',
		contractEnd: '',
		phone: '',
		email: '',
		titles: '',
		biography: '',
		linkToTheaterSite: '',
		wikiUrl: ''
	},
	{
		fullName: 'БЕНИШ  Александр Альбертович',
		position: 'директор',
		organization: 'ГБУК г. Москвы "МДТ "Модернъ"',
		organizationInn: '7701127897',
		hrId: '8',
		photo: '8.jpg',
		contractStart: '',
		contractEnd: '',
		phone: '',
		email: '',
		titles: '',
		biography: '',
		linkToTheaterSite: '',
		wikiUrl: ''
	},
	{
		fullName: 'БЕРЕСТОВ  Дмитрий Юрьевич',
		position: 'директор',
		organization: 'ГБУК г. Москвы "Московский государственный театр "Ленком Марка Захарова"',
		organizationInn: '7707062124',
		hrId: '9',
		photo: '9.jpg',
		contractStart: '',
		contractEnd: '',
		phone: '',
		email: '',
		titles: '',
		biography: '',
		linkToTheaterSite: '',
		wikiUrl: ''
	},
	{
		fullName: 'БЕРЕСТОВ  Дмитрий Юрьевич',
		position: 'директор',
		organization: 'ГБУК г. Москвы "Театр на Юго-Западе"',
		organizationInn: '7729217597',
		hrId: '9',
		photo: '9.jpg',
		contractStart: '',
		contractEnd: '',
		phone: '',
		email: '',
		titles: '',
		biography: '',
		linkToTheaterSite: '',
		wikiUrl: ''
	},
	{
		fullName: 'БЕРТМАН  Дмитрий Александрович',
		position: 'генеральный директор',
		organization: 'ГБУК г. Москвы "ММТ "Геликон-опера"',
		organizationInn: '7703063504',
		hrId: '10',
		photo: '10.jpg',
		contractStart: '',
		contractEnd: '',
		phone: '',
		email: '',
		titles: '',
		biography: '',
		linkToTheaterSite: '',
		wikiUrl: ''
	},
	{
		fullName: 'БЕРТМАН  Дмитрий Александрович',
		position: 'художественный руководитель',
		organization: 'ГБУК г. Москвы "ММТ "Геликон-опера"',
		organizationInn: '7703063504',
		hrId: '10',
		photo: '10.jpg',
		contractStart: '',
		contractEnd: '',
		phone: '',
		email: '',
		titles: '',
		biography: '',
		linkToTheaterSite: '',
		wikiUrl: ''
	},
	{
		fullName: 'БОГОМОЛОВ Константин Юрьевич',
		position: 'художественный руководитель',
		organization: 'ГБУК г. Москвы "Театр на Малой Бронной"',
		organizationInn: '7703001970',
		hrId: '11',
		photo: '11.jpg',
		contractStart: '',
		contractEnd: '',
		phone: '',
		email: '',
		titles: '',
		biography: '',
		linkToTheaterSite: '',
		wikiUrl: ''
	},
	{
		fullName: 'БОРИСОВ Андрей Александрович',
		position: 'генеральный директор',
		organization: 'ГБУК г. Москвы "МАМТ"',
		organizationInn: '7710081367',
		hrId: '12',
		photo: '12.jpg',
		contractStart: '',
		contractEnd: '',
		phone: '',
		email: '',
		titles: '',
		biography: '',
		linkToTheaterSite: '',
		wikiUrl: ''
	},
	{
		fullName: 'БОЧАРНИКОВ Александр Сергеевич',
		position: 'директор',
		organization: 'ГБУК г. Москвы "МДТ им. Н.В. Гоголя"',
		organizationInn: '7709018353',
		hrId: '13',
		photo: '13.jpg',
		contractStart: '',
		contractEnd: '',
		phone: '',
		email: '',
		titles: '',
		biography: '',
		linkToTheaterSite: '',
		wikiUrl: ''
	},
	{
		fullName: 'БРУСНИКИНА Марина Станиславовна',
		position: 'художественный руководитель',
		organization: 'ГБУК г. Москвы "Театр "Практика"',
		organizationInn: '7710593781',
		hrId: '14',
		photo: '14.jpg',
		contractStart: '',
		contractEnd: '',
		phone: '',
		email: '',
		titles: '',
		biography: '',
		linkToTheaterSite: '',
		wikiUrl: ''
	},
	{
		fullName: 'ВИЛЬКИН Александр Михайлович',
		position: 'художественный руководитель',
		organization: 'ГБУК г. Москвы "МТЦ "Вишневый сад" п/р А. Вилькина"',
		organizationInn: '7704132084',
		hrId: '15',
		photo: '15.jpg',
		contractStart: '',
		contractEnd: '',
		phone: '',
		email: '',
		titles: '',
		biography: '',
		linkToTheaterSite: '',
		wikiUrl: ''
	},
	{
		fullName: 'ВОРОБЬЁВ Андрей Михайлович',
		position: 'директор',
		organization: 'ГБУК г.Москвы "Московский театр "Мастерская П.Н. Фоменко"',
		organizationInn: '7703002886',
		hrId: '16',
		photo: '16.jpg',
		contractStart: '',
		contractEnd: '',
		phone: '',
		email: '',
		titles: '',
		biography: '',
		linkToTheaterSite: '',
		wikiUrl: ''
	},
	{
		fullName: 'ГЕРАСИМОВ Евгений Владимирович',
		position: 'художественный руководитель',
		organization: 'ГБУК г. Москвы "Московский академический театр сатиры"',
		organizationInn: '7710002492',
		hrId: '17',
		photo: '17.jpg',
		contractStart: '',
		contractEnd: '',
		phone: '',
		email: '',
		titles: '',
		biography: '',
		linkToTheaterSite: '',
		wikiUrl: ''
	},
	{
		fullName: 'ГЕРАСИМОВ Евгений Владимирович',
		position: 'художественный руководитель',
		organization: 'ГБУК г. Москвы "Театр на Малой Ордынке"',
		organizationInn: '7710018171',
		hrId: '17',
		photo: '17.jpg',
		contractStart: '',
		contractEnd: '',
		phone: '',
		email: '',
		titles: '',
		biography: '',
		linkToTheaterSite: '',
		wikiUrl: ''
	},
	{
		fullName: 'ГЕТЬМАН Антон Александрович',
		position: 'директор',
		organization: 'ГБУК МТ "Новая Опера" им. Е.В.Колобова',
		organizationInn: '7704249283',
		hrId: '18',
		photo: '18.jpg',
		contractStart: '',
		contractEnd: '',
		phone: '',
		email: '',
		titles: '',
		biography: '',
		linkToTheaterSite: '',
		wikiUrl: ''
	},
	{
		fullName: 'ГОЛДОВСКИЙ Борис Павлович',
		position: 'художественный руководитель',
		organization: 'ГБУК г. Москвы "Московский театр кукол"',
		organizationInn: '7701109200',
		hrId: '19',
		photo: '19.jpg',
		contractStart: '',
		contractEnd: '',
		phone: '',
		email: '',
		titles: '',
		biography: '',
		linkToTheaterSite: '',
		wikiUrl: ''
	},
	{
		fullName: 'ГРИБАНОВА Марина Борисовна',
		position: 'художественный руководитель',
		organization: 'ГБУК г.Москвы "МТДК "Волшебная лампа"',
		organizationInn: '7708107804',
		hrId: '20',
		photo: '20.jpg',
		contractStart: '',
		contractEnd: '',
		phone: '',
		email: '',
		titles: '',
		biography: '',
		linkToTheaterSite: '',
		wikiUrl: ''
	},
	{
		fullName: 'ГРИШУНИН  Глеб Павлович',
		position: 'директор',
		organization: 'ГБУК г. Москвы "Центр драматургии и режиссуры"',
		organizationInn: '7722284474',
		hrId: '21',
		photo: '21.jpg',
		contractStart: '',
		contractEnd: '',
		phone: '',
		email: '',
		titles: '',
		biography: '',
		linkToTheaterSite: '',
		wikiUrl: ''
	},
	{
		fullName: 'ГРОМОВА Наталья Васильевна',
		position: 'исполняющая обязанности директора',
		organization: 'ГБУК г. Москвы "Центр Славы Полунина"',
		organizationInn: '#N/A',
		hrId: '22',
		photo: '22.jpg',
		contractStart: '',
		contractEnd: '',
		phone: '',
		email: '',
		titles: '',
		biography: '',
		linkToTheaterSite: '',
		wikiUrl: ''
	},
	{
		fullName: 'ГРЫМОВ Юрий Вячеславович',
		position: 'художественный руководитель',
		organization: 'ГБУК г. Москвы "МДТ "Модернъ"',
		organizationInn: '7701127897',
		hrId: '23',
		photo: '23.jpg',
		contractStart: '',
		contractEnd: '',
		phone: '',
		email: '',
		titles: '',
		biography: '',
		linkToTheaterSite: '',
		wikiUrl: ''
	},
	{
		fullName: 'ДАДАМЯН Арсен Геннадьевич',
		position: 'директор',
		organization: 'ГБУК г. Москвы "ДМТЮА"',
		organizationInn: '7707120908',
		hrId: '24',
		photo: '24.jpg',
		contractStart: '',
		contractEnd: '',
		phone: '',
		email: '',
		titles: '',
		biography: '',
		linkToTheaterSite: '',
		wikiUrl: ''
	},
	{
		fullName: 'ДЕВЯТОВ Владимир Сергеевич',
		position: 'художественный руководитель',
		organization: 'ГБУК г. Москвы "ФЦ "Москва"',
		organizationInn: '7730116466',
		hrId: '25',
		photo: '25.jpg',
		contractStart: '',
		contractEnd: '',
		phone: '',
		email: '',
		titles: '',
		biography: '',
		linkToTheaterSite: '',
		wikiUrl: ''
	},
	{
		fullName: 'ДОЛГАЧЕВ Вячеслав Васильевич',
		position: 'художественный руководитель',
		organization: 'ГБУК г. Москвы "Новый драматический театр"',
		organizationInn: '7716028803',
		hrId: '26',
		photo: '26.jpg',
		contractStart: '',
		contractEnd: '',
		phone: '',
		email: '',
		titles: '',
		biography: '',
		linkToTheaterSite: '',
		wikiUrl: ''
	},
	{
		fullName: 'ДУРОВА Наталья Юрьевна',
		position: 'художественный руководитель',
		organization: 'ГБУК г. Москвы "Театр "Уголок дедушки Дурова"',
		organizationInn: '7702061293',
		hrId: '27',
		photo: '27.jpg',
		contractStart: '',
		contractEnd: '',
		phone: '',
		email: '',
		titles: '',
		biography: '',
		linkToTheaterSite: '',
		wikiUrl: ''
	},
	{
		fullName: 'ДУРОВА Тереза Ганнибаловна',
		position: 'художественный руководитель',
		organization: 'ГБУК г. Москвы "Театриум на Серпуховке под руководством Терезы Дуровой"',
		organizationInn: '#N/A',
		hrId: '28',
		photo: '28.jpg',
		contractStart: '',
		contractEnd: '',
		phone: '',
		email: '',
		titles: '',
		biography: '',
		linkToTheaterSite: '',
		wikiUrl: ''
	},
	{
		fullName: 'ЖУКОВ Владимир Иванович',
		position: 'директор',
		organization: 'ГБУК г. Москвы "МДТ им. А.С. Пушкина"',
		organizationInn: '7703035553',
		hrId: '29',
		photo: '29.jpg',
		contractStart: '05.07.2022',
		contractEnd: '07.07.2025',
		phone: '79629135575',
		email: 'ZhukovVI1@culture.mos.ru',
		titles: '',
		biography: '',
		linkToTheaterSite: '',
		wikiUrl: ''
	},
	{
		fullName: 'ЗАСЛАВСКИЙ Константин Яковлевич',
		position: 'директор',
		organization: 'ГБУК г. Москвы "Московский театр ОКОЛО"',
		organizationInn: '7703068710',
		hrId: '30',
		photo: '30.jpg',
		contractStart: '',
		contractEnd: '',
		phone: '',
		email: '',
		titles: '',
		biography: '',
		linkToTheaterSite: '',
		wikiUrl: ''
	},
	{
		fullName: 'ЗАХАРОВА Ирина Валентиновна',
		position: 'директор',
		organization: 'ГБУК г.Москвы "Театр Музыки и Поэзии п/р Е.Камбуровой"',
		organizationInn: '7702078561',
		hrId: '31',
		photo: '31.jpg',
		contractStart: '',
		contractEnd: '',
		phone: '',
		email: '',
		titles: '',
		biography: '',
		linkToTheaterSite: '',
		wikiUrl: ''
	},
	{
		fullName: 'ЗОЛИНА Ирина Вячеславовна',
		position: 'директор',
		organization: 'ГБУК г. Москвы "МДТ им. К.С. Станиславского"',
		organizationInn: '7710009515',
		hrId: '32',
		photo: '32.jpg',
		contractStart: '',
		contractEnd: '',
		phone: '',
		email: '',
		titles: '',
		biography: '',
		linkToTheaterSite: '',
		wikiUrl: ''
	},
	{
		fullName: 'КАЛЯГИН Александр',
		position: 'художественный руководитель',
		organization: 'ГБУК г. Москвы "Московский театр "ET CETERA"',
		organizationInn: '#N/A',
		hrId: '33',
		photo: '33.jpg',
		contractStart: '',
		contractEnd: '',
		phone: '',
		email: '',
		titles: '',
		biography: '',
		linkToTheaterSite: '',
		wikiUrl: ''
	},
	{
		fullName: 'КАМБУРОВА Елена Антоновна',
		position: 'художественный руководитель',
		organization: 'ГБУК г.Москвы "Театр Музыки и Поэзии п/р Е.Камбуровой"',
		organizationInn: '7702078561',
		hrId: '34',
		photo: '34.jpg',
		contractStart: '',
		contractEnd: '',
		phone: '',
		email: '',
		titles: '',
		biography: '',
		linkToTheaterSite: '',
		wikiUrl: ''
	},
	{
		fullName: 'КАМЕНЬКОВИЧ Евгений Борисович',
		position: 'художественный руководитель',
		organization: 'ГБУК г.Москвы "Московский театр "Мастерская П.Н. Фоменко"',
		organizationInn: '7703002886',
		hrId: '35',
		photo: '35.jpg',
		contractStart: '',
		contractEnd: '',
		phone: '',
		email: '',
		titles: '',
		biography: '',
		linkToTheaterSite: '',
		wikiUrl: ''
	},
	{
		fullName: 'КОВАЛЕЦ Ирина Владимировна',
		position: 'директор',
		organization: 'ГБУК г. Москвы "Детский театр эстрады"',
		organizationInn: '7710042865',
		hrId: '36',
		photo: '36.jpg',
		contractStart: '',
		contractEnd: '',
		phone: '',
		email: '',
		titles: '',
		biography: '',
		linkToTheaterSite: '',
		wikiUrl: ''
	},
	{
		fullName: 'КРЯЧУН Ирина Ивановна',
		position: 'художественный руководитель',
		organization: 'ГБУК г. Москвы "Театр марионеток"',
		organizationInn: '7701199901',
		hrId: '37',
		photo: '37.jpg',
		contractStart: '',
		contractEnd: '',
		phone: '',
		email: '',
		titles: '',
		biography: '',
		linkToTheaterSite: '',
		wikiUrl: ''
	},
	{
		fullName: 'КУЗОЯТОВ Сергей Валерьевич',
		position: 'директор',
		organization: 'ГБУК "МДТ им. М.Н. Ермоловой"',
		organizationInn: '7710143327',
		hrId: '38',
		photo: '38.jpg',
		contractStart: '',
		contractEnd: '',
		phone: '',
		email: '',
		titles: '',
		biography: '',
		linkToTheaterSite: '',
		wikiUrl: ''
	},
	{
		fullName: 'КУЗЬМАКОВА Елена Алексеевна',
		position: 'директор',
		organization: 'ГБУК г. Москвы "Театр "Практика"',
		organizationInn: '7710593781',
		hrId: '39',
		photo: '39.jpg',
		contractStart: '',
		contractEnd: '',
		phone: '',
		email: '',
		titles: '',
		biography: '',
		linkToTheaterSite: '',
		wikiUrl: ''
	},
	{
		fullName: 'КУКЛАЧЕВ Юрий Дмитриевич',
		position: 'художественный руководитель',
		organization: 'ГБУК г. Москвы "Театр кошек Куклачева"',
		organizationInn: '7730519779',
		hrId: '40',
		photo: '40.jpg',
		contractStart: '',
		contractEnd: '',
		phone: '',
		email: '',
		titles: '',
		biography: '',
		linkToTheaterSite: '',
		wikiUrl: ''
	},
	{
		fullName: 'КУРОЧКИН Павел Викторович',
		position: 'художественный руководитель',
		organization: 'ГБУК г.Москвы "Ведогонь-театр"',
		organizationInn: '7735026248',
		hrId: '41',
		photo: '41.jpg',
		contractStart: '',
		contractEnd: '',
		phone: '',
		email: '',
		titles: '',
		biography: '',
		linkToTheaterSite: '',
		wikiUrl: ''
	},
	{
		fullName: 'ЛАПШИНА Екатерина Николаевна',
		position: 'директор',
		organization: 'ГБУК г. Москвы "Московский академический театр им. Вл. Маяковского"',
		organizationInn: '7703025812',
		hrId: '42',
		photo: '42.jpg',
		contractStart: '',
		contractEnd: '',
		phone: '',
		email: '',
		titles: '',
		biography: '',
		linkToTheaterSite: '',
		wikiUrl: ''
	},
	{
		fullName: 'ЛЕВИТИН Михаил Захарович',
		position: 'художественный руководитель',
		organization: 'ГБУК г. Москвы "Театр Эрмитаж"',
		organizationInn: '7707085202',
		hrId: '43',
		photo: '43.jpg',
		contractStart: '',
		contractEnd: '',
		phone: '',
		email: '',
		titles: '',
		biography: '',
		linkToTheaterSite: '',
		wikiUrl: ''
	},
	{
		fullName: 'ЛЕУШИН Олег Николаевич',
		position: 'художественный руководитель',
		organization: 'ГБУК г. Москвы "Театр на Юго-Западе"',
		organizationInn: '7729217597',
		hrId: '44',
		photo: '44.jpg',
		contractStart: '',
		contractEnd: '',
		phone: '',
		email: '',
		titles: '',
		biography: '',
		linkToTheaterSite: '',
		wikiUrl: ''
	},
	{
		fullName: 'ЛИПОВЕЦКИЙ Олег Михайлович',
		position: 'художественный руководитель',
		organization: 'ГБУК г. Москвы "Театр "Шалом"',
		organizationInn: '7726073570',
		hrId: '45',
		photo: '45.jpg',
		contractStart: '',
		contractEnd: '',
		phone: '',
		email: '',
		titles: '',
		biography: '',
		linkToTheaterSite: '',
		wikiUrl: ''
	},
	{
		fullName: 'МАРЧЕЛЛИ Евгений Жозефович',
		position: 'художественный руководитель',
		organization: 'ГБУК г.Москвы "Театр им. Моссовета"',
		organizationInn: '7710040730',
		hrId: '46',
		photo: '46.jpg',
		contractStart: '',
		contractEnd: '',
		phone: '',
		email: '',
		titles: '',
		biography: '',
		linkToTheaterSite: '',
		wikiUrl: ''
	},
	{
		fullName: 'МАШКОВ Владимир Львович',
		position: 'художественный руководитель',
		organization: 'ГБУК г. Москвы "Театр Олега Табакова"',
		organizationInn: '7701117909',
		hrId: '47',
		photo: '47.jpg',
		contractStart: '',
		contractEnd: '',
		phone: '',
		email: '',
		titles: '',
		biography: '',
		linkToTheaterSite: '',
		wikiUrl: ''
	},
	{
		fullName: 'МАШКОВ Владимир Львович',
		position: 'директор',
		organization: '"Московский театр "Современник"',
		organizationInn: '7701046341',
		hrId: '47',
		photo: '47.jpg',
		contractStart: '',
		contractEnd: '',
		phone: '',
		email: '',
		titles: '',
		biography: '',
		linkToTheaterSite: '',
		wikiUrl: ''
	},
	{
		fullName: 'МЕЛЬНИКОВ  Иван Александрович',
		position: 'директор',
		organization: 'ГБУК г.Москвы "Московский музыкальный театр "На Басманной"',
		organizationInn: '7701258410',
		hrId: '48',
		photo: '48.jpg',
		contractStart: '',
		contractEnd: '',
		phone: '',
		email: '',
		titles: '',
		biography: '',
		linkToTheaterSite: '',
		wikiUrl: ''
	},
	{
		fullName: 'МЕНЬШИКОВ Олег Евгеньевич',
		position: 'художественный руководитель',
		organization: 'ГБУК "МДТ им. М.Н. Ермоловой"',
		organizationInn: '7710143327',
		hrId: '49',
		photo: '49.jpg',
		contractStart: '',
		contractEnd: '',
		phone: '',
		email: '',
		titles: '',
		biography: '',
		linkToTheaterSite: '',
		wikiUrl: ''
	},
	{
		fullName: 'МЕСХИШВИЛИ Владимир Георгиевич',
		position: 'директор',
		organization: 'ГБУК г. Москвы "Московский драматический театр "Человек"',
		organizationInn: '7703127934',
		hrId: '50',
		photo: '50.jpg',
		contractStart: '',
		contractEnd: '',
		phone: '',
		email: '',
		titles: '',
		biography: '',
		linkToTheaterSite: '',
		wikiUrl: ''
	},
	{
		fullName: 'МИЗЮКОВ Михаил Александрович',
		position: 'художественный руководитель',
		organization: 'ГБУК "Московский государственный историко-этнографический театр"',
		organizationInn: '#N/A',
		hrId: '51',
		photo: '51.jpg',
		contractStart: '',
		contractEnd: '',
		phone: '',
		email: '',
		titles: '',
		biography: '',
		linkToTheaterSite: '',
		wikiUrl: ''
	},
	{
		fullName: 'МИКОЯН Анастас Алексеевич',
		position: 'художественный руководитель',
		organization: 'ГБУК г. Москвы "Театр Стаса Намина"',
		organizationInn: '7723316672',
		hrId: '52',
		photo: '52.jpg',
		contractStart: '',
		contractEnd: '',
		phone: '',
		email: '',
		titles: '',
		biography: '',
		linkToTheaterSite: '',
		wikiUrl: ''
	},
	{
		fullName: 'МИЛЕНИНА Ирина Петровна',
		position: 'художественный руководитель',
		organization: 'ГБУК г. Москвы "МД "Сказочный театр"',
		organizationInn: '7709264045',
		hrId: '53',
		photo: '53.jpg',
		contractStart: '',
		contractEnd: '',
		phone: '',
		email: '',
		titles: '',
		biography: '',
		linkToTheaterSite: '',
		wikiUrl: ''
	},
	{
		fullName: 'МОГИНОВ Альберт Рафисович',
		position: 'директор',
		organization: 'ГБУК г. Москвы "Московский детский музыкально-драматический театр"',
		organizationInn: '7721032971',
		hrId: '54',
		photo: '54.jpg',
		contractStart: '',
		contractEnd: '',
		phone: '',
		email: '',
		titles: '',
		biography: '',
		linkToTheaterSite: '',
		wikiUrl: ''
	},
	{
		fullName: 'МОГИНОВА Анастасия Рафисовна',
		position: 'директор',
		organization: 'ГБУК г. Москвы "Театр Эрмитаж"',
		organizationInn: '7707085202',
		hrId: '55',
		photo: '55.jpg',
		contractStart: '',
		contractEnd: '',
		phone: '',
		email: '',
		titles: '',
		biography: '',
		linkToTheaterSite: '',
		wikiUrl: ''
	},
	{
		fullName: 'МОДЕСТОВА Маргарита Андреевна',
		position: 'директор',
		organization: 'ГБУК "Московский детский театр теней"',
		organizationInn: '#N/A',
		hrId: '56',
		photo: '56.jpg',
		contractStart: '',
		contractEnd: '',
		phone: '',
		email: '',
		titles: '',
		biography: '',
		linkToTheaterSite: '',
		wikiUrl: ''
	},
	{
		fullName: 'НЕРОВНАЯ Анна Михайловна',
		position: 'художественный руководитель',
		organization: 'ГБУК г. Москвы МДТ "Бенефис"',
		organizationInn: '7728039292',
		hrId: '57',
		photo: '57.jpg',
		contractStart: '',
		contractEnd: '',
		phone: '',
		email: '',
		titles: '',
		biography: '',
		linkToTheaterSite: '',
		wikiUrl: ''
	},
	{
		fullName: 'НЕРУШ Людмила Викторовна',
		position: 'директор',
		organization: 'ГБУК "МТК "Жар-птица"',
		organizationInn: '7701020760',
		hrId: '58',
		photo: '58.jpg',
		contractStart: '',
		contractEnd: '',
		phone: '',
		email: '',
		titles: '',
		biography: '',
		linkToTheaterSite: '',
		wikiUrl: ''
	},
	{
		fullName: 'НЕСМЕЛОВА Наталия Михайловна',
		position: 'директор',
		organization: 'ГБУК "Московский театр "На досках"',
		organizationInn: '7703014835',
		hrId: '59',
		photo: '59.jpg',
		contractStart: '',
		contractEnd: '',
		phone: '',
		email: '',
		titles: '',
		biography: '',
		linkToTheaterSite: '',
		wikiUrl: ''
	},
	{
		fullName: 'НЕСТРАТОВ Павел Вячеславович',
		position: 'директор',
		organization: 'ГБУК г. Москвы "Московский академический театр сатиры"',
		organizationInn: '7710002492',
		hrId: '60',
		photo: '60.jpg',
		contractStart: '',
		contractEnd: '',
		phone: '',
		email: '',
		titles: '',
		biography: '',
		linkToTheaterSite: '',
		wikiUrl: ''
	},
	{
		fullName: 'НЕСТРАТОВ Павел Вячеславович',
		position: 'директор',
		organization: 'ГБУК г. Москвы "Театр на Малой Ордынке"',
		organizationInn: '7710018171',
		hrId: '60',
		photo: '60.jpg',
		contractStart: '',
		contractEnd: '',
		phone: '',
		email: '',
		titles: '',
		biography: '',
		linkToTheaterSite: '',
		wikiUrl: ''
	},
	{
		fullName: 'ОВСЯННИКОВ Валентин Валентинович',
		position: 'художественный руководитель',
		organization: 'ГБУК г. Москвы "Детский театр эстрады"',
		organizationInn: '7710042865',
		hrId: '61',
		photo: '61.jpg',
		contractStart: '',
		contractEnd: '',
		phone: '',
		email: '',
		titles: '',
		biography: '',
		linkToTheaterSite: '',
		wikiUrl: ''
	},
	{
		fullName: 'ПАВЛОВ Игорь Борисович',
		position: 'директор',
		organization: 'ГБУК г. Москвы "МГИЭТ"',
		organizationInn: '7716149741',
		hrId: '62',
		photo: '62.jpg',
		contractStart: '',
		contractEnd: '',
		phone: '',
		email: '',
		titles: '',
		biography: '',
		linkToTheaterSite: '',
		wikiUrl: ''
	},
	{
		fullName: 'ПАНКОВ Владимир Николаевич',
		position: 'художественный руководитель',
		organization: 'ГБУК г. Москвы "Московский государственный театр "Ленком Марка Захарова"',
		organizationInn: '7707062124',
		hrId: '63',
		photo: '63.jpg',
		contractStart: '',
		contractEnd: '',
		phone: '',
		email: '',
		titles: '',
		biography: '',
		linkToTheaterSite: '',
		wikiUrl: ''
	},
	{
		fullName: 'ПАНКОВ Владимир Николаевич',
		position: 'художественный руководитель',
		organization: 'ГБУК г. Москвы "Центр драматургии и режиссуры"',
		organizationInn: '7722284474',
		hrId: '63',
		photo: '63.jpg',
		contractStart: '',
		contractEnd: '',
		phone: '',
		email: '',
		titles: '',
		biography: '',
		linkToTheaterSite: '',
		wikiUrl: ''
	},
	{
		fullName: 'ПЕПЕЛЯЕВА Ольга Юрьевна',
		position: 'директор',
		organization: 'ГБУК г. Москвы "Театр на Покровке"',
		organizationInn: '7701045549',
		hrId: '64',
		photo: '64.jpg',
		contractStart: '',
		contractEnd: '',
		phone: '',
		email: '',
		titles: '',
		biography: '',
		linkToTheaterSite: '',
		wikiUrl: ''
	},
	{
		fullName: 'ПЕРЕГУДОВ Георгий Михайлович',
		position: 'художественный руководитель',
		organization: 'ГБУК г. Москвы "Московский академический театр им. Вл. Маяковского"',
		organizationInn: '7703025812',
		hrId: '65',
		photo: '65.jpg',
		contractStart: '',
		contractEnd: '',
		phone: '',
		email: '',
		titles: '',
		biography: '',
		linkToTheaterSite: '',
		wikiUrl: ''
	},
	{
		fullName: 'ПИСАРЕВ Евгений Александрович',
		position: 'художественный руководитель',
		organization: 'ГБУК г. Москвы "МДТ им. А.С. Пушкина"',
		organizationInn: '7703035553',
		hrId: '66',
		photo: '66.jpg',
		contractStart: '',
		contractEnd: '',
		phone: '74956941338',
		email: 'pisarev@teatrpushkin.ru',
		titles: 'Заслуженный артист России (2006)',
		biography: '',
		linkToTheaterSite: 'https://teatrpushkin.ru/persona/detail/pisarev-evgeniy-aleksandrovich/',
		wikiUrl:
			'https://ru.wikipedia.org/wiki/%D0%9F%D0%B8%D1%81%D0%B0%D1%80%D0%B5%D0%B2,_%D0%95%D0%B2%D0%B3%D0%B5%D0%BD%D0%B8%D0%B9_%D0%90%D0%BB%D0%B5%D0%BA%D1%81%D0%B0%D0%BD%D0%B4%D1%80%D0%BE%D0%B2%D0%B8%D1%87'
	},
	{
		fullName: 'ПОГРЕБНИЧКО Юрий Николаевич',
		position: 'художественный руководитель',
		organization: 'ГБУК г. Москвы "Московский театр ОКОЛО"',
		organizationInn: '7703068710',
		hrId: '67',
		photo: '67.jpg',
		contractStart: '',
		contractEnd: '',
		phone: '',
		email: '',
		titles: '',
		biography: '',
		linkToTheaterSite: '',
		wikiUrl: ''
	},
	{
		fullName: 'ПОЛЕТАЕВ  Алексей Валерьевич',
		position: 'директор',
		organization: 'ГБУК г. Москвы "Центр исполнительских искусств на Добрынинский"',
		organizationInn: '#N/A',
		hrId: '68',
		photo: '68.jpg',
		contractStart: '',
		contractEnd: '',
		phone: '',
		email: '',
		titles: '',
		biography: '',
		linkToTheaterSite: '',
		wikiUrl: ''
	},
	{
		fullName: 'ПОПОВ Игорь Павлович',
		position: 'директор',
		organization: 'ГБУК г. Москвы "Мастерская "12" Никиты Михалкова", Мастерская "12"',
		organizationInn: '7704060947',
		hrId: '69',
		photo: '69.jpg',
		contractStart: '',
		contractEnd: '',
		phone: '',
		email: '',
		titles: '',
		biography: '',
		linkToTheaterSite: '',
		wikiUrl: ''
	},
	{
		fullName: 'ПОПОВИЧЕВА  Вера Илларионовна',
		position: 'директор',
		organization: 'ГБУК г. Москвы "Новый драматический театр"',
		organizationInn: '7716028803',
		hrId: '70',
		photo: '70.jpg',
		contractStart: '',
		contractEnd: '',
		phone: '',
		email: '',
		titles: '',
		biography: '',
		linkToTheaterSite: '',
		wikiUrl: ''
	},
	{
		fullName: 'РЕВЗИНА Татьяна Иосифовна',
		position: 'директор',
		organization: 'ГБУК г. Москвы',
		organizationInn: '#N/A',
		hrId: '71',
		photo: '71.jpg',
		contractStart: '',
		contractEnd: '',
		phone: '',
		email: '',
		titles: '',
		biography: '',
		linkToTheaterSite: '',
		wikiUrl: ''
	},
	{
		fullName: 'РЕДЬКО Людмила Викторовна',
		position: 'директор',
		organization: 'ГБУК г. Москвы "Московский театр кукол"',
		organizationInn: '7701109200',
		hrId: '72',
		photo: '72.jpg',
		contractStart: '',
		contractEnd: '',
		phone: '',
		email: '',
		titles: '',
		biography: '',
		linkToTheaterSite: '',
		wikiUrl: ''
	},
	{
		fullName: 'РОЗОВСКИЙ Марк Григорьевич',
		position: 'художественный руководитель',
		organization: 'ГБУК г. Москвы',
		organizationInn: '#N/A',
		hrId: '73',
		photo: '73.jpg',
		contractStart: '',
		contractEnd: '',
		phone: '',
		email: '',
		titles: '',
		biography: '',
		linkToTheaterSite: '',
		wikiUrl: ''
	},
	{
		fullName: 'РОМАНЦОВА Наталья Николаевна',
		position: 'директор',
		organization: 'ГБУК г. Москвы "Цыганский театр "Ромэн"',
		organizationInn: '7714035227',
		hrId: '74',
		photo: '74.jpg',
		contractStart: '',
		contractEnd: '',
		phone: '',
		email: '',
		titles: '',
		biography: '',
		linkToTheaterSite: '',
		wikiUrl: ''
	},
	{
		fullName: 'РЫБНИКОВ Алексей Львович',
		position: 'художественный руководитель',
		organization: 'ГБУК г. Москвы " Центр исполнительских искусств на Добрынинский "',
		organizationInn: '#N/A',
		hrId: '75',
		photo: '75.jpg',
		contractStart: '',
		contractEnd: '',
		phone: '',
		email: '',
		titles: '',
		biography: '',
		linkToTheaterSite: '',
		wikiUrl: ''
	},
	{
		fullName: 'СЕРГИЕНКО Николай Николаевич',
		position: 'художественный руководитель',
		organization: 'ГБУК г. Москвы "Цыганский театр "Ромэн"',
		organizationInn: '7714035227',
		hrId: '76',
		photo: '76.jpg',
		contractStart: '',
		contractEnd: '',
		phone: '',
		email: '',
		titles: '',
		biography: '',
		linkToTheaterSite: '',
		wikiUrl: ''
	},
	{
		fullName: 'СЛЮСАРЕВА Ирина Федоровна',
		position: 'директор',
		organization: 'ГБУК "Московский театр Юного Зрителя"',
		organizationInn: '#N/A',
		hrId: '77',
		photo: '77.jpg',
		contractStart: '',
		contractEnd: '',
		phone: '',
		email: '',
		titles: '',
		biography: '',
		linkToTheaterSite: '',
		wikiUrl: ''
	},
	{
		fullName: 'СОКОЛОВА Ольга Эдуардовна',
		position: 'директор',
		organization: 'ГБУК г. Москвы "Школа драматического искусства"',
		organizationInn: '7702619852',
		hrId: '78',
		photo: '78.jpg',
		contractStart: '',
		contractEnd: '',
		phone: '',
		email: '',
		titles: '',
		biography: '',
		linkToTheaterSite: '',
		wikiUrl: ''
	},
	{
		fullName: 'СПЕСИВЦЕВ Вячеслав Семёнович',
		position: 'художественный руководитель',
		organization: 'ГБУК г. Москвы "ММЭТ п/р В.Спесивцева"',
		organizationInn: '7715049230',
		hrId: '79',
		photo: '79.jpg',
		contractStart: '',
		contractEnd: '',
		phone: '',
		email: '',
		titles: '',
		biography: '',
		linkToTheaterSite: '',
		wikiUrl: ''
	},
	{
		fullName: 'СУХОВ Федор Владимирович',
		position: 'художественный руководитель',
		organization: 'ГБУК г. Москвы ДДТ "На набережной"',
		organizationInn: '7704224472',
		hrId: '80',
		photo: '80.jpg',
		contractStart: '',
		contractEnd: '',
		phone: '',
		email: '',
		titles: '',
		biography: '',
		linkToTheaterSite: '',
		wikiUrl: ''
	},
	{
		fullName: 'ТАРТАКОВСКИЙ Владимир Израилевич',
		position: 'художественный руководитель',
		organization: 'ГБУК г.Москвы "Московская оперетта"',
		organizationInn: '#N/A',
		hrId: '81',
		photo: '81.jpg',
		contractStart: '',
		contractEnd: '',
		phone: '',
		email: '',
		titles: '',
		biography: '',
		linkToTheaterSite: '',
		wikiUrl: ''
	},
	{
		fullName: 'ТЕРТЕРЯН Жаннета Гургеновна',
		position: 'художественный руководитель',
		organization: 'ГБУК г.Москвы "Московский музыкальный театр "На Басманной"',
		organizationInn: '7701258410',
		hrId: '82',
		photo: '82.jpg',
		contractStart: '',
		contractEnd: '',
		phone: '',
		email: '',
		titles: '',
		biography: '',
		linkToTheaterSite: '',
		wikiUrl: ''
	},
	{
		fullName: 'ФАТЕЕВА Марина Валерьевна',
		position: 'директор',
		organization: 'Директор ГБУК г. Москвы "Фольклорный центр "Москва"',
		organizationInn: '#N/A',
		hrId: '83',
		photo: '83.jpg',
		contractStart: '',
		contractEnd: '',
		phone: '',
		email: '',
		titles: '',
		biography: '',
		linkToTheaterSite: '',
		wikiUrl: ''
	},
	{
		fullName: 'ФЕДОРОВ Александр Львович',
		position: 'художественный руководитель',
		organization: 'ГБУК г. Москвы "ДМТЮА"',
		organizationInn: '7707120908',
		hrId: '84',
		photo: '84.jpg',
		contractStart: '',
		contractEnd: '',
		phone: '',
		email: '',
		titles: '',
		biography: '',
		linkToTheaterSite: '',
		wikiUrl: ''
	},
	{
		fullName: 'ХАЗАНОВ Геннадий Викторович',
		position: 'художественный руководитель',
		organization: 'ГБУК г. Москвы "Московский театр Эстрады"',
		organizationInn: '7706089941',
		hrId: '85',
		photo: '85.jpg',
		contractStart: '',
		contractEnd: '',
		phone: '',
		email: '',
		titles: '',
		biography: '',
		linkToTheaterSite: '',
		wikiUrl: ''
	},
	{
		fullName: 'ЧЕРЕПНЕВ Алексей Анатольевич',
		position: 'директор',
		organization: 'ГБУК г. Москвы "Театр',
		organizationInn: '#N/A',
		hrId: '86',
		photo: '86.jpg',
		contractStart: '',
		contractEnd: '',
		phone: '',
		email: '',
		titles: '',
		biography: '',
		linkToTheaterSite: '',
		wikiUrl: ''
	},
	{
		fullName: 'ЮХАНАНОВ Борис Юрьевич',
		position: 'художественный руководитель',
		organization: 'ГБУК г. Москвы "МДТ',
		organizationInn: '#N/A',
		hrId: '87',
		photo: '87.jpg',
		contractStart: '',
		contractEnd: '',
		phone: '',
		email: '',
		titles: '',
		biography: '',
		linkToTheaterSite: '',
		wikiUrl: ''
	},
	{
		fullName: 'ЯКОВЛЕВ Антон Юрьевич',
		position: 'художественный руководитель',
		organization: 'ГБУК г. Москвы "МДТ им.',
		organizationInn: '#N/A',
		hrId: '88',
		photo: '88.jpg',
		contractStart: '',
		contractEnd: '',
		phone: '',
		email: '',
		titles: '',
		biography: '',
		linkToTheaterSite: '',
		wikiUrl: ''
	},
	{
		fullName: 'ЯКОВЛЕВА  Валентина Юрьевна',
		position: 'директор',
		organization: 'ГБУК г. Москвы "Театр \nна Малой Бронной"',
		organizationInn: '#N/A',
		hrId: '89',
		photo: '89.jpg',
		contractStart: '',
		contractEnd: '',
		phone: '',
		email: '',
		titles: '',
		biography: '',
		linkToTheaterSite: '',
		wikiUrl: ''
	},
	{
		fullName: 'ЯНОВСКАЯ Генриэта Наумовна',
		position: 'художественный руководитель',
		organization: 'ГБУК "Московский Театр Юного Зрителя"',
		organizationInn: '#N/A',
		hrId: '90',
		photo: '90.jpg',
		contractStart: '',
		contractEnd: '',
		phone: '',
		email: '',
		titles: '',
		biography: '',
		linkToTheaterSite: '',
		wikiUrl: ''
	},
	{
		fullName: 'Татьяна Романовна Носачева',
		position: 'пресс-служба',
		organization: 'ГБУК г. Москвы "МДТ им. А.С. Пушкина"',
		organizationInn: '7703035553',
		hrId: '91',
		photo: '91.jpg',
		contractStart: '',
		contractEnd: '',
		phone: '74956941695',
		email: 'press@teatrpushkin.ru',
		titles: '',
		biography: '',
		linkToTheaterSite: '',
		wikiUrl: ''
	},
	{
		fullName: 'Алентова Вера Валентиновна',
		position: 'топовые артисты',
		organization: 'ГБУК г. Москвы "МДТ им. А.С. Пушкина"',
		organizationInn: '7703035553',
		hrId: '92',
		photo: '92.jpg',
		contractStart: '',
		contractEnd: '',
		phone: '',
		email: '',
		titles:
			'Народная артистка России (1992)\n\nЛауреат Государственной премии СССР\n\nЛауреат Государственной премии им. братьев Васильевых',
		biography:
			'После окончания Школы-студии МХАТ в 1965 году Вера Алентова была принята в труппу Театра имени Пушкина. Ее первой ролью на сцене нашего театра стала Райна в спектакле «Шоколадный солдатик» режиссера Бориса Равенских.\n\nС 2009 года руководит актерско-режиссерской мастерской во ВГИКе.\n\nДебют в кино состоялся в 1965 году в фильме о советских пилотах «Дни летные». Самой знаменитой картиной с Верой Алентовой в главной роли стала режиссерская работа Владимира Меньшова — фильм «Москва слезам не верит» (1979).\n\nСреди других киноработ — роли в фильмах «Завтра была война», «Жених из Майами», «Ширли-мырли», «Зависть богов», «Серебряная свадьба», «Дар божий», «И все-таки я люблю...», «Бальзаковский возраст, или все мужики сво...», «Дорога без конца», «Воскресенье» и др.',
		linkToTheaterSite: 'https://teatrpushkin.ru/persona/detail/alentova-vera-valentinovna/',
		wikiUrl:
			'https://ru.wikipedia.org/wiki/%D0%90%D0%BB%D0%B5%D0%BD%D1%82%D0%BE%D0%B2%D0%B0,_%D0%92%D0%B5%D1%80%D0%B0_%D0%92%D0%B0%D0%BB%D0%B5%D0%BD%D1%82%D0%B8%D0%BD%D0%BE%D0%B2%D0%BD%D0%B0'
	},
	{
		fullName: 'Арсентьев Александр Сергеевич',
		position: 'топовые артисты',
		organization: 'ГБУК г. Москвы "МДТ им. А.С. Пушкина"',
		organizationInn: '7703035553',
		hrId: '93',
		photo: '93.jpg',
		contractStart: '',
		contractEnd: '',
		phone: '',
		email: '',
		titles: 'Заслуженный артист России (2021)\n\nПочётный деятель искусств города Москвы (2017)',
		biography:
			'В 1999-2001 гг. — актер МХТ им. А. П. Чехова. Дебютировал на сцене Художественного театра в спектакле «Маленькие трагедии» (Альберт). Играл в спектаклях: «Пролетный гусь», «Сонечка», «Лесная песня», «Сирано де Бержерак» и др.\n\nС 2001 года Александр Арсентьев — актер труппы театра имени А. С. Пушкина. Его первая роль в нашем театра — Печорин в спектакле Михаила Мокеева «Зовите Печориным» , затем — Меркуцио в спектакле Романа Козака «Ромео и Джульетта».\n\nИсполнил роль герцога Орсино в спектакле Деклана Доннеллана «Двенадцатая ночь» (Международная конфедерация театральных союзов).\n\nВ мюзикле «Чикаго» (Стейдж Энтертейнмент) исполнил роль Билла Финна.\n\nВ кино Александр Арсентьев дебютировал в 1998 году, сыграв роль поручика Сокольского в многосерийной киноленте «Чехов и Ко».\nСнимался в фильмах: «Марш Турецкого», «МУР есть МУР», «Атлантида», «Тяжелый песок», «Новая жизнь сыщика Гурова», «Институт благородных девиц», «Любовь по расписанию», «Государыня и разбойник», «Танго с ангелом», «Новогодняя жена», «Поцелуй в голову», «Под небом Вероны», «Адъютанты любви», «Юрочка», «Ангелина», «Почти семейный детектив» и др.',
		linkToTheaterSite: 'https://teatrpushkin.ru/persona/detail/arsentiev-aleksandr-sergeevich/',
		wikiUrl:
			'https://ru.wikipedia.org/wiki/%D0%90%D1%80%D1%81%D0%B5%D0%BD%D1%82%D1%8C%D0%B5%D0%B2,_%D0%90%D0%BB%D0%B5%D0%BA%D1%81%D0%B0%D0%BD%D0%B4%D1%80_%D0%A1%D0%B5%D1%80%D0%B3%D0%B5%D0%B5%D0%B2%D0%B8%D1%87'
	},
	{
		fullName: 'Бякова Ирина Александровна',
		position: 'топовые артисты',
		organization: 'ГБУК г. Москвы "МДТ им. А.С. Пушкина"',
		organizationInn: '7703035553',
		hrId: '94',
		photo: '94.jpg',
		contractStart: '',
		contractEnd: '',
		phone: '',
		email: '',
		titles: 'Заслуженная артистка России',
		biography: '',
		linkToTheaterSite: 'https://teatrpushkin.ru/persona/detail/byakova-irina-aleksandrovna/',
		wikiUrl:
			'https://ru.wikipedia.org/wiki/%D0%91%D1%8F%D0%BA%D0%BE%D0%B2%D0%B0,_%D0%98%D1%80%D0%B8%D0%BD%D0%B0_%D0%90%D0%BB%D0%B5%D0%BA%D1%81%D0%B0%D0%BD%D0%B4%D1%80%D0%BE%D0%B2%D0%BD%D0%B0'
	},
	{
		fullName: 'Жеребцов Владимир Евгеньевич',
		position: 'топовые артисты',
		organization: 'ГБУК г. Москвы "МДТ им. А.С. Пушкина"',
		organizationInn: '7703035553',
		hrId: '95',
		photo: '95.jpg',
		contractStart: '',
		contractEnd: '',
		phone: '',
		email: '',
		titles: 'Почётный деятель искусств города Москвы (2021)',
		biography: '',
		linkToTheaterSite: 'https://teatrpushkin.ru/persona/detail/zherebtsov-vladimir-evgenievich/',
		wikiUrl:
			'https://ru.wikipedia.org/wiki/%D0%96%D0%B5%D1%80%D0%B5%D0%B1%D1%86%D0%BE%D0%B2,_%D0%92%D0%BB%D0%B0%D0%B4%D0%B8%D0%BC%D0%B8%D1%80_%D0%95%D0%B2%D0%B3%D0%B5%D0%BD%D1%8C%D0%B5%D0%B2%D0%B8%D1%87'
	},
	{
		fullName: 'Заводюк Андрей Валерьевич',
		position: 'топовые артисты',
		organization: 'ГБУК г. Москвы "МДТ им. А.С. Пушкина"',
		organizationInn: '7703035553',
		hrId: '96',
		photo: '96.jpg',
		contractStart: '',
		contractEnd: '',
		phone: '',
		email: '',
		titles: 'Заслуженный артист России (2018)\n\nПочётный деятель искусств города Москвы (2016)',
		biography: '',
		linkToTheaterSite: 'https://teatrpushkin.ru/persona/detail/zavodyuk-andrey-valerievich/',
		wikiUrl:
			'https://ru.wikipedia.org/wiki/%D0%97%D0%B0%D0%B2%D0%BE%D0%B4%D1%8E%D0%BA,_%D0%90%D0%BD%D0%B4%D1%80%D0%B5%D0%B9_%D0%92%D0%B0%D0%BB%D0%B5%D1%80%D1%8C%D0%B5%D0%B2%D0%B8%D1%87'
	},
	{
		fullName: 'Исакова Виктория Евгеньевна',
		position: 'топовые артисты',
		organization: 'ГБУК г. Москвы "МДТ им. А.С. Пушкина"',
		organizationInn: '7703035553',
		hrId: '97',
		photo: '97.jpg',
		contractStart: '',
		contractEnd: '',
		phone: '',
		email: '',
		titles: 'Заслуженная артистка России (2019)',
		biography: '',
		linkToTheaterSite: 'https://teatrpushkin.ru/persona/detail/isakova-viktoriya-evgenievna/',
		wikiUrl:
			'https://ru.wikipedia.org/wiki/%D0%98%D1%81%D0%B0%D0%BA%D0%BE%D0%B2%D0%B0,_%D0%92%D0%B8%D0%BA%D1%82%D0%BE%D1%80%D0%B8%D1%8F_%D0%95%D0%B2%D0%B3%D0%B5%D0%BD%D1%8C%D0%B5%D0%B2%D0%BD%D0%B0'
	},
	{
		fullName: 'Кара-Моско Инна Витальевна',
		position: 'топовые артисты',
		organization: 'ГБУК г. Москвы "МДТ им. А.С. Пушкина"',
		organizationInn: '7703035553',
		hrId: '98',
		photo: '98.jpg',
		contractStart: '',
		contractEnd: '',
		phone: '',
		email: '',
		titles: 'Заслуженная артистка России',
		biography: '',
		linkToTheaterSite: 'https://teatrpushkin.ru/persona/detail/kara-mosko-inna-vitalievna/',
		wikiUrl:
			'https://ru.wikipedia.org/wiki/%D0%9A%D0%B0%D1%80%D0%B0-%D0%9C%D0%BE%D1%81%D0%BA%D0%BE,_%D0%98%D0%BD%D0%BD%D0%B0_%D0%92%D0%B8%D1%82%D0%B0%D0%BB%D1%8C%D0%B5%D0%B2%D0%BD%D0%B0'
	},
	{
		fullName: 'Кузичев Андрей Владимирович',
		position: 'топовые артисты',
		organization: 'ГБУК г. Москвы "МДТ им. А.С. Пушкина"',
		organizationInn: '7703035553',
		hrId: '99',
		photo: '99.jpg',
		contractStart: '',
		contractEnd: '',
		phone: '',
		email: '',
		titles: 'Почётный деятель искусств города Москвы (2023)',
		biography: '',
		linkToTheaterSite: 'https://teatrpushkin.ru/persona/detail/kuzichev-andrey-vladimirovich/',
		wikiUrl:
			'https://ru.wikipedia.org/wiki/%D0%9A%D1%83%D0%B7%D0%B8%D1%87%D0%B5%D0%B2,_%D0%90%D0%BD%D0%B4%D1%80%D0%B5%D0%B9_%D0%92%D0%BB%D0%B0%D0%B4%D0%B8%D0%BC%D0%B8%D1%80%D0%BE%D0%B2%D0%B8%D1%87'
	},
	{
		fullName: 'Майзингер Владимир Александрович',
		position: 'топовые артисты',
		organization: 'ГБУК г. Москвы "МДТ им. А.С. Пушкина"',
		organizationInn: '7703035553',
		hrId: '100',
		photo: '100.jpg',
		contractStart: '',
		contractEnd: '',
		phone: '',
		email: '',
		titles: 'Заслуженный артист России (2019)',
		biography: '',
		linkToTheaterSite: 'https://teatrpushkin.ru/persona/detail/mayzinger-vladimir-aleksandrovich/',
		wikiUrl: 'https://www.kino-teatr.ru/kino/acter/m/ros/302269/bio/'
	},
	{
		fullName: 'Марушина Нина Александровна',
		position: 'топовые артисты',
		organization: 'ГБУК г. Москвы "МДТ им. А.С. Пушкина"',
		organizationInn: '7703035553',
		hrId: '101',
		photo: '101.jpg',
		contractStart: '',
		contractEnd: '',
		phone: '',
		email: '',
		titles: 'Заслуженная артистка России (1995)',
		biography: '',
		linkToTheaterSite: 'https://teatrpushkin.ru/persona/detail/marushina-nina-aleksandrovna/',
		wikiUrl: 'https://www.kino-teatr.ru/kino/acter/w/ros/2724/works/'
	},
	{
		fullName: 'Матросов Александр Валерьевич',
		position: 'топовые артисты',
		organization: 'ГБУК г. Москвы "МДТ им. А.С. Пушкина"',
		organizationInn: '7703035553',
		hrId: '102',
		photo: '102.jpg',
		contractStart: '',
		contractEnd: '',
		phone: '',
		email: '',
		titles: 'Почётный деятель искусств города Москвы (2020)',
		biography: '',
		linkToTheaterSite: 'https://teatrpushkin.ru/persona/detail/matrosov-aleksandr-valerievich/',
		wikiUrl: 'https://www.kino-teatr.ru/kino/acter/m/ros/2764/bio/'
	},
	{
		fullName: 'Николаева Наталья Ивановна',
		position: 'топовые артисты',
		organization: 'ГБУК г. Москвы "МДТ им. А.С. Пушкина"',
		organizationInn: '7703035553',
		hrId: '103',
		photo: '103.jpg',
		contractStart: '',
		contractEnd: '',
		phone: '',
		email: '',
		titles: 'Заслуженная артистка России',
		biography: '',
		linkToTheaterSite: 'https://teatrpushkin.ru/persona/detail/nikolaeva-natalya-ivanovna/',
		wikiUrl: 'https://www.kino-teatr.ru/teatr/acter/w/sov/40963/bio/'
	},
	{
		fullName: 'Панина Анастасия Владимировна',
		position: 'топовые артисты',
		organization: 'ГБУК г. Москвы "МДТ им. А.С. Пушкина"',
		organizationInn: '7703035553',
		hrId: '104',
		photo: '104.jpg',
		contractStart: '',
		contractEnd: '',
		phone: '',
		email: '',
		titles: '',
		biography: '',
		linkToTheaterSite: 'https://teatrpushkin.ru/persona/detail/panina-anastasiya-vladimirovna/',
		wikiUrl:
			'https://ru.wikipedia.org/wiki/%D0%9F%D0%B0%D0%BD%D0%B8%D0%BD%D0%B0,_%D0%90%D0%BD%D0%B0%D1%81%D1%82%D0%B0%D1%81%D0%B8%D1%8F_%D0%92%D0%BB%D0%B0%D0%B4%D0%B8%D0%BC%D0%B8%D1%80%D0%BE%D0%B2%D0%BD%D0%B0'
	},
	{
		fullName: 'Попова Нина Георгиевна',
		position: 'топовые артисты',
		organization: 'ГБУК г. Москвы "МДТ им. А.С. Пушкина"',
		organizationInn: '7703035553',
		hrId: '105',
		photo: '105.jpg',
		contractStart: '',
		contractEnd: '',
		phone: '',
		email: '',
		titles: 'Заслуженная артистка России (1984)',
		biography: '',
		linkToTheaterSite: 'https://teatrpushkin.ru/persona/detail/popova-nina-georgievna/',
		wikiUrl:
			'https://ru.wikipedia.org/wiki/%D0%9F%D0%BE%D0%BF%D0%BE%D0%B2%D0%B0,_%D0%9D%D0%B8%D0%BD%D0%B0_%D0%93%D0%B5%D0%BE%D1%80%D0%B3%D0%B8%D0%B5%D0%B2%D0%BD%D0%B0'
	},
	{
		fullName: 'Урсуляк Александра Сергеевна',
		position: 'топовые артисты',
		organization: 'ГБУК г. Москвы "МДТ им. А.С. Пушкина"',
		organizationInn: '7703035553',
		hrId: '106',
		photo: '106.jpg',
		contractStart: '',
		contractEnd: '',
		phone: '',
		email: '',
		titles: 'Почётный деятель искусств города Москвы (2020)',
		biography: '',
		linkToTheaterSite: 'https://teatrpushkin.ru/persona/detail/ursulyak-aleksandra-sergeevna/',
		wikiUrl:
			'https://ru.wikipedia.org/wiki/%D0%A3%D1%80%D1%81%D1%83%D0%BB%D1%8F%D0%BA,_%D0%90%D0%BB%D0%B5%D0%BA%D1%81%D0%B0%D0%BD%D0%B4%D1%80%D0%B0_%D0%A1%D0%B5%D1%80%D0%B3%D0%B5%D0%B5%D0%B2%D0%BD%D0%B0'
	}
];
